version: '3'

services:
  server:
    build: ./server
    command: python .
    ports:
      - 7777:7777
    volumes:
      - ./server:/app

  client:
    build: ./client
    command: python .
    ports:
      - 7778:7778
    depends_on:
      - server
    volumes:
      - ./client:/app
